// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Accounts struct {
	ID         int32
	OwnerID    pgtype.Int4
	CurrencyID pgtype.Int4
	Balance    pgtype.Int8
}

type BankExchangeRates struct {
	ID             int32
	BankID         pgtype.Int2
	CurrencyFromID int32
	CurrencyToID   int32
	Date           pgtype.Date
	Rate           int32
}

type Banks struct {
	ID             int16
	PlanetID       int32
	OrganizationID int32
	Name           string
}

type Currencies struct {
	ID             int32
	Code           string
	Name           string
	OrganizationID int32
}

type MarketOrders struct {
	ID        int32
	UserID    int32
	PairID    int32
	Amount    int64
	Price     int64
	Status    pgtype.Bool
	CreatedAt pgtype.Timestamp
}

type MarketPairs struct {
	ID             int32
	CurrencySellID int32
	CurrencyBuyID  int32
}

type MarketTrades struct {
	ID          int32
	OrderSellID int32
	OrderBuyID  int32
	Amount      int64
	Price       int64
	CreatedAt   pgtype.Timestamp
}

type Transactions struct {
	ID            int32
	FromAccountID int32
	ToAccountID   int32
	Amount        int64
	CurrencyID    int32
	Reason        pgtype.Text
	UserComment   pgtype.Text
	CreatedAt     pgtype.Timestamp
}
