// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: accounts.sql

package db

import (
	"context"
)

const SelectAccount = `-- name: SelectAccount :one
SELECT
    id,
    owner_id,
    owner_type,
    bank_id,
    currency_id,
    balance,
    is_reserve
FROM
    accounts
WHERE
    id = $1
    LIMIT 1
`

func (q *Queries) SelectAccount(ctx context.Context, id int32) (Accounts, error) {
	row := q.db.QueryRow(ctx, SelectAccount, id)
	var i Accounts
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.OwnerType,
		&i.BankID,
		&i.CurrencyID,
		&i.Balance,
		&i.IsReserve,
	)
	return i, err
}
