// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Accounts struct {
	ID         int32
	OwnerID    int32
	OwnerType  pgtype.Text
	BankID     pgtype.Int4
	CurrencyID pgtype.Int4
	Balance    pgtype.Int8
	IsReserve  pgtype.Bool
}

type BankExchangeRates struct {
	ID             int32
	BankID         pgtype.Int4
	CurrencyFromID pgtype.Int4
	CurrencyToID   pgtype.Int4
	Date           pgtype.Timestamp
	Rate           int64
}

type Banks struct {
	ID         int32
	PlanetID   int32
	Code       int32
	Name       string
	OwnerID    int32
	CurrencyID int32
}

type Currencies struct {
	ID   int32
	Code string
	Name string
}

type MarketOrders struct {
	ID             int32
	UserID         pgtype.Int4
	CurrencySellID pgtype.Int4
	AmountSell     int64
	CurrencyBuyID  pgtype.Int4
	Price          int64
	OrderType      pgtype.Text
	Status         pgtype.Text
	CreatedAt      pgtype.Timestamp
}

type MarketTrades struct {
	ID             int32
	OrderSellID    pgtype.Int4
	OrderBuyID     pgtype.Int4
	CurrencySellID pgtype.Int4
	AmountSell     int64
	CurrencyBuyID  pgtype.Int4
	Price          int64
	CreatedAt      pgtype.Timestamp
}

type Transactions struct {
	ID              int32
	FromAccountID   pgtype.Int4
	ToAccountID     pgtype.Int4
	Amount          int64
	CurrencyID      pgtype.Int4
	TransactionType pgtype.Text
}
